services:
    hackzilla_ticket.listener:
        class: Hackzilla\Bundle\TicketBundle\EventListener\UserLoad
        arguments:
            - '%hackzilla_ticket.model.user.class%'
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    hackzilla_ticket_user_extension:
        class: Hackzilla\Bundle\TicketBundle\Extension\UserExtension
        arguments: ['@hackzilla_ticket.user_manager']
        tags:
            - { name: twig.extension }

    hackzilla_ticket.user_manager:
        class: Hackzilla\Bundle\TicketBundle\Manager\UserManager
        arguments:
            - '@security.token_storage'
            - '@hackzilla_ticket.user_repository'

    hackzilla_ticket.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%hackzilla_ticket.model.user.class%'

    hackzilla_ticket.ticket_manager:
        class: Hackzilla\Bundle\TicketBundle\Manager\TicketManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%hackzilla_ticket.model.ticket.class%'
            - '%hackzilla_ticket.model.message.class%'

    hackzilla_ticket.form.type.ticket:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketType
        arguments:
            - '%hackzilla_ticket.model.ticket.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket }

    hackzilla_ticket.form.type.ticket_message:
        class: Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType
        arguments:
            - '@hackzilla_ticket.user_manager'
            - '%hackzilla_ticket.model.message.class%'
        tags:
            - { name: form.type, alias: hackzilla_ticket_message }
